"""empty message

Revision ID: 0c7421036dd6
Revises: bf2ef9b9b644
Create Date: 2021-05-29 21:54:20.466779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7421036dd6'
down_revision = 'bf2ef9b9b644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=192), nullable=True),
    sa.Column('district', sa.String(length=192), nullable=True),
    sa.Column('city', sa.String(length=192), nullable=True),
    sa.Column('pin', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stauts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId'),
    sa.UniqueConstraint('teamId')
    )
    op.create_table('tech_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.String(length=7), nullable=False),
    sa.Column('gid', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('rgukt_location', sa.String(length=50), nullable=True),
    sa.Column('collegeId', sa.String(length=30), nullable=True),
    sa.Column('idcard_url', sa.String(length=128), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('branch', sa.String(length=3), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('registration_status', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=True),
    sa.Column('referral', sa.String(length=30), nullable=True),
    sa.Column('survey', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('gid'),
    sa.UniqueConstraint('gid'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('userId'),
    sa.UniqueConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_user')
    op.drop_table('team')
    op.drop_table('member')
    op.drop_table('address')
    # ### end Alembic commands ###
