"""empty message

Revision ID: 2643d0f24285
Revises: 26fd71aa55de
Create Date: 2021-05-31 23:42:21.332812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2643d0f24285'
down_revision = '26fd71aa55de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('tzId', sa.String(length=7), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=True),
    sa.Column('recipt_no', sa.Integer(), nullable=True),
    sa.Column('tkt_type', sa.String(length=30), nullable=True),
    sa.Column('barcode_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
