"""empty message

Revision ID: 26fd71aa55de
Revises: 3db19ac93f6f
Create Date: 2021-05-31 18:56:58.289481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fd71aa55de'
down_revision = '3db19ac93f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workshop_payment_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_user', schema=None) as batch_op:
        batch_op.drop_column('workshop_payment_status')

    # ### end Alembic commands ###
