"""empty message

Revision ID: 382276daf400
Revises: 07bcb5aec612
Create Date: 2021-06-04 20:26:19.091259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382276daf400'
down_revision = '07bcb5aec612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=7), nullable=False),
    sa.Column('event_title', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tech_user.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('current_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_team_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventId', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('event_title', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('team_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('team_status')
        batch_op.drop_column('event_title')
        batch_op.drop_column('eventId')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('userId')

    with op.batch_alter_table('current_id', schema=None) as batch_op:
        batch_op.drop_column('current_team_id')

    op.drop_table('team_request')
    # ### end Alembic commands ###
