"""empty message

Revision ID: 3db19ac93f6f
Revises: 967ad637501c
Create Date: 2021-05-31 17:59:53.874965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db19ac93f6f'
down_revision = '967ad637501c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workshop_id', sa.String(length=7), nullable=True))
        batch_op.create_foreign_key(None, 'workshop', ['workshop_id'], ['workshopId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workshop_id')

    # ### end Alembic commands ###
