"""empty message

Revision ID: 495e505e4d6a
Revises: c6b79d0b0856
Create Date: 2021-06-07 00:48:25.168007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495e505e4d6a'
down_revision = 'c6b79d0b0856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_issue', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
