"""empty message

Revision ID: 63842a37f0f9
Revises: 9912c7f0ca82
Create Date: 2021-06-04 12:38:05.172447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63842a37f0f9'
down_revision = '9912c7f0ca82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_title', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_request', schema=None) as batch_op:
        batch_op.drop_column('event_title')

    # ### end Alembic commands ###
