"""empty message

Revision ID: 7dba9165712c
Revises: bf4bb82d148b
Create Date: 2021-05-30 12:40:02.284370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dba9165712c'
down_revision = 'bf4bb82d148b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('caId', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('branch', sa.String(length=3), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caId'),
    sa.UniqueConstraint('caId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CA')
    # ### end Alembic commands ###
