"""empty message

Revision ID: 8c3e1c73cb1a
Revises: a763a03458db
Create Date: 2021-05-22 18:55:56.621684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3e1c73cb1a'
down_revision = 'a763a03458db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_id',
    sa.Column('current_techzite_id', sa.Integer(), nullable=False),
    sa.Column('current_event_id', sa.Integer(), nullable=True),
    sa.Column('current_workshop_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('current_techzite_id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=128), nullable=False),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=192), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.Column('dept', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('eventId', sa.String(length=7), nullable=False),
    sa.Column('dept', sa.String(length=5), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('brief', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('structure', sa.String(length=2000), nullable=True),
    sa.Column('timeline', sa.String(length=2000), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('rules', sa.String(length=2000), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('min_teamsize', sa.SmallInteger(), nullable=True),
    sa.Column('max_teamsize', sa.SmallInteger(), nullable=True),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.Column('organiser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organiser_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId'),
    sa.UniqueConstraint('organiser_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('workshopId', sa.String(length=7), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('dept', sa.String(length=5), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('timeline', sa.String(length=500), nullable=True),
    sa.Column('resources', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshopId')
    )
    op.create_table('FAQ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('event_id', sa.String(length=7), nullable=True),
    sa.Column('workshop_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.eventId'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.workshopId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('event_id', sa.String(length=7), nullable=True),
    sa.Column('workshop_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.eventId'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.workshopId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('event_id', sa.String(length=7), nullable=True),
    sa.Column('workshop_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.eventId'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.workshopId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor')
    op.drop_table('contact')
    op.drop_table('FAQ')
    op.drop_table('workshop')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('sessions')
    op.drop_table('image')
    op.drop_table('current_id')
    # ### end Alembic commands ###
