"""empty message

Revision ID: 9912c7f0ca82
Revises: d211b143f634
Create Date: 2021-06-04 12:36:20.321232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9912c7f0ca82'
down_revision = 'd211b143f634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_title', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_request', schema=None) as batch_op:
        batch_op.drop_column('event_title')

    # ### end Alembic commands ###
