"""empty message

Revision ID: 9b8dd6616b46
Revises: 63842a37f0f9
Create Date: 2021-06-04 18:36:51.696809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8dd6616b46'
down_revision = '63842a37f0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
