"""empty message

Revision ID: b02c08b620dc
Revises: bfca5fc9e4fc
Create Date: 2021-05-27 12:43:39.961805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b02c08b620dc'
down_revision = 'bfca5fc9e4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('collegeId')

    with op.batch_alter_table('tech_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collegeId', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.Integer(), nullable=True))

    with op.batch_alter_table('workshop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    with op.batch_alter_table('tech_user', schema=None) as batch_op:
        batch_op.drop_column('hidden')
        batch_op.drop_column('collegeId')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collegeId', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
