"""empty message

Revision ID: b74acbd34309
Revises: 495e505e4d6a
Create Date: 2021-06-07 00:58:57.344439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b74acbd34309'
down_revision = '495e505e4d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_issue', schema=None) as batch_op:
        # batch_op.drop_index('user_id')
        # batch_op.drop_index('user_id_2')
        pass

    op.drop_table('payment_issue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_issue',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('payment_type', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tech_user.userId'], name='payment_issue_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('payment_issue', schema=None) as batch_op:
        batch_op.create_index('user_id_2', ['user_id'], unique=False)
        batch_op.create_index('user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
