"""empty message

Revision ID: be5ced676cb1
Revises: 8c3e1c73cb1a
Create Date: 2021-05-22 19:01:19.381679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be5ced676cb1'
down_revision = '8c3e1c73cb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
