"""empty message

Revision ID: bf4bb82d148b
Revises: 
Create Date: 2021-05-30 12:33:24.559458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4bb82d148b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_id',
    sa.Column('current_techzite_id', sa.Integer(), nullable=False),
    sa.Column('current_event_id', sa.Integer(), nullable=True),
    sa.Column('current_workshop_id', sa.Integer(), nullable=True),
    sa.Column('current_ca_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('current_techzite_id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=128), nullable=False),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('tech_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.String(length=7), nullable=False),
    sa.Column('gid', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('rgukt_location', sa.String(length=50), nullable=True),
    sa.Column('collegeId', sa.String(length=30), nullable=True),
    sa.Column('idcard_url', sa.String(length=128), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('branch', sa.String(length=3), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('registration_status', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=True),
    sa.Column('referral', sa.String(length=30), nullable=True),
    sa.Column('survey', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('gid'),
    sa.UniqueConstraint('gid'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('userId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=192), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.Column('dept', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('userId'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=192), nullable=True),
    sa.Column('district', sa.String(length=192), nullable=True),
    sa.Column('city', sa.String(length=192), nullable=True),
    sa.Column('pin', sa.String(length=10), nullable=True),
    sa.Column('t_userId', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['t_userId'], ['tech_user.userId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('t_userId'),
    sa.UniqueConstraint('t_userId')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('eventId', sa.String(length=7), nullable=False),
    sa.Column('dept', sa.String(length=5), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('brief', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('structure', sa.String(length=2000), nullable=True),
    sa.Column('timeline', sa.String(length=2000), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('rules', sa.String(length=2000), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('min_teamsize', sa.SmallInteger(), nullable=True),
    sa.Column('max_teamsize', sa.SmallInteger(), nullable=True),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.Column('organiser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organiser_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId'),
    sa.UniqueConstraint('eventId'),
    sa.UniqueConstraint('organiser_id'),
    sa.UniqueConstraint('organiser_id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('title')
    )
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('workshopId', sa.String(length=7), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('dept', sa.String(length=5), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('timeline', sa.String(length=500), nullable=True),
    sa.Column('resources', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coordinator_id'),
    sa.UniqueConstraint('coordinator_id'),
    sa.UniqueConstraint('workshopId'),
    sa.UniqueConstraint('workshopId')
    )
    op.create_table('FAQ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('event_id', sa.String(length=7), nullable=True),
    sa.Column('workshop_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.eventId'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.workshopId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('event_id', sa.String(length=7), nullable=True),
    sa.Column('workshop_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.eventId'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.workshopId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('hidden', sa.SmallInteger(), nullable=True),
    sa.Column('event_id', sa.String(length=7), nullable=True),
    sa.Column('workshop_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.eventId'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.workshopId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamId', sa.String(length=7), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId'),
    sa.UniqueConstraint('teamId')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stauts', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tech_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    op.drop_table('team')
    op.drop_table('sponsor')
    op.drop_table('contact')
    op.drop_table('FAQ')
    op.drop_table('workshop')
    op.drop_table('event')
    op.drop_table('address')
    op.drop_table('user')
    op.drop_table('tech_user')
    op.drop_table('sessions')
    op.drop_table('image')
    op.drop_table('current_id')
    # ### end Alembic commands ###
