"""empty message

Revision ID: c76dbce5f5ee
Revises: f28473c3f4d2
Create Date: 2021-06-05 17:56:27.163351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76dbce5f5ee'
down_revision = 'f28473c3f4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=15), nullable=True),
    sa.Column('counter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counter_id'], ['counter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_address')
    # ### end Alembic commands ###
