"""empty message

Revision ID: d8c2c3a7c958
Revises: b74acbd34309
Create Date: 2021-06-07 01:03:59.048127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c2c3a7c958'
down_revision = 'b74acbd34309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=7), nullable=True),
    sa.Column('payment_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tech_user.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_issue')
    # ### end Alembic commands ###
