"""empty message

Revision ID: f28473c3f4d2
Revises: 382276daf400
Create Date: 2021-06-05 16:26:02.154811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28473c3f4d2'
down_revision = '382276daf400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.teamId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id'),
    sa.UniqueConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    # ### end Alembic commands ###
